@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.satherov.crystalix.datagen;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;