@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.satherov.crystalix.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;