@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.satherov.crystalix.plugin;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;