@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.satherov.crystalix.content.properties;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;