@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.satherov.crystalix.network;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;